# Radio Station Configuration
# Comment out stations with # to disable them

# Target artists and songs to check
target_artists:
  - Phil Collins
  - Genesis
  - Bad Bunny

target_songs:
  - Africa

relisten:
  SLAM!: slam
  Radio 538: 538
  NPO 3FM: 3fm
  Q Music: qmusic
  100% NL: 100p
  Sky Radio: skyradio
  Radio Veronica: veronica
  Radio 10: radio10
  Arrow Classic Rock: arrow
  RadioNL: radionl
  NPO Radio 1: radio1
  NPO Radio 2: radio2
  NPO Radio 5: radio5
  KINK: kink
  JOE: joe
  # Note: Homepage rotates ~19 stations at a time

myonlineradio:
  100% NL: 100procent-nl
  Arrow Classic Rock: arrow-classic-rock
  JOE: joe
  KINK: kink
  NPO 3FM: npo-3fm
  NPO Radio 1: npo-radio-1
  NPO Radio 2: npo-radio-2
  NPO Radio 5: npo-radio-5
  Q Music: q-music
  Radio 10: radio-10
  Radio 538: radio-538
  RadioNL: radionl
  Sky Radio: sky-radio
  SLAM!: slam
  Radio Veronica: veronica

playlist24:
  100% NL: 100pnl-playlist
  Arrow Classic Rock: arrow-classic-rock-playlist
  KINK: kink-playlist
  NPO 3FM: 3fm-playlist
  NPO Radio 1: radio-1-playlist
  NPO Radio 2: radio-2-playlist
  NPO Radio 5: radio-5-playlist
  Q Music: qmusic-playlist
  Radio 10: radio-10-playlist
  Radio 538: radio-538-playlist
  Sky Radio: skyradio-playlist
  SLAM!: slamfm-playlist
